# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290d6a580e8c5ea037bab4b7741582882f5a1dd2842373a73c8b39366eb0c907053753b24368ec1d3d6eaa08c4474374fb0199d927bd783dacfd080e7a50595e

test:
  secret_key_base: e388454510534c90eecfa2671067aaf635ed7e4a37e0076e10c85bfc09ab0e98b657c3a58c11cca8e2804f7e77b53a919327109bf28961c8412d7da21bd9bb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
